### ISSUE TITLE
Error when adding package to meteor

### ISSUE THREAD

**Issue by airedale302** [vijayanant/meteor-yahoo-oauth#1]
=> Errors while adding packages:

While selecting package versions:
error: unknown package: isobuild:isopack-2
Required by: vijayanant:meteor-yahoo-oauth 1.0.0

The package failed to be added.

**Comment by vijayanant** [comment]
Updated version dependencies

**Comment by airedale302** [comment]
Unfortunately, the same error persists, although the version number has changed:

 => Errors while adding packages:

While selecting package versions:
error: unknown package: isobuild:isopack-2
Required by: vijayanant:meteor-yahoo-oauth 1.0.1

**Comment by airedale302** [comment]
Unfortunately, the same error persists, although the version number has changed:

 => Errors while adding packages:

While selecting package versions:
error: unknown package: isobuild:isopack-2
Required by: vijayanant:meteor-yahoo-oauth 1.0.1

**Comment by airedale302** [comment]
Unfortunately, the same error persists, although the version number has changed:

 => Errors while adding packages:

While selecting package versions:
error: unknown package: isobuild:isopack-2
Required by: vijayanant:meteor-yahoo-oauth 1.0.1

**Comment by airedale302** [comment]
Unfortunately, the same error persists, although the version number has changed:

 => Errors while adding packages:

While selecting package versions:
error: unknown package: isobuild:isopack-2
Required by: vijayanant:meteor-yahoo-oauth 1.0.1

**Comment by airedale302** [comment]
Unfortunately, the same error persists, although the version number has changed:

 => Errors while adding packages:

While selecting package versions:
error: unknown package: isobuild:isopack-2
Required by: vijayanant:meteor-yahoo-oauth 1.0.1

**Comment by airedale302** [comment]
Unfortunately, the same error persists, although the version number has changed:

 => Errors while adding packages:

While selecting package versions:
error: unknown package: isobuild:isopack-2
Required by: vijayanant:meteor-yahoo-oauth 1.0.1

**Comment by airedale302** [comment]
Unfortunately, the same error persists, although the version number has changed:

 => Errors while adding packages:

While selecting package versions:
error: unknown package: isobuild:isopack-2
Required by: vijayanant:meteor-yahoo-oauth 1.0.1

**Comment by airedale302** [comment]
Unfortunately, the same error persists, although the version number has changed:

 => Errors while adding packages:

While selecting package versions:
error: unknown package: isobuild:isopack-2
Required by: vijayanant:meteor-yahoo-oauth 1.0.1

**Comment by airedale302** [comment]
Unfortunately, the same error persists, although the version number has changed:

 => Errors while adding packages:

While selecting package versions:
error: unknown package: isobuild:isopack-2
Required by: vijayanant:meteor-yahoo-oauth 1.0.1

**Comment by airedale302** [comment]
Unfortunately, the same error persists, although the version number has changed:

 => Errors while adding packages:

While selecting package versions:
error: unknown package: isobuild:isopack-2
Required by: vijayanant:meteor-yahoo-oauth 1.0.1

**Comment by airedale302** [comment]
Unfortunately, the same error persists, although the version number has changed:

 => Errors while adding packages:

While selecting package versions:
error: unknown package: isobuild:isopack-2
Required by: vijayanant:meteor-yahoo-oauth 1.0.1

**Comment by airedale302** [comment]
Unfortunately, the same error persists, although the version number has changed:

 => Errors while adding packages:

While selecting package versions:
error: unknown package: isobuild:isopack-2
Required by: vijayanant:meteor-yahoo-oauth 1.0.1

**Comment by airedale302** [comment]
Unfortunately, the same error persists, although the version number has changed:

 => Errors while adding packages:

While selecting package versions:
error: unknown package: isobuild:isopack-2
Required by: vijayanant:meteor-yahoo-oauth 1.0.1

**Comment by airedale302** [comment]
Unfortunately, the same error persists, although I can see the version
number of the package has changed:

 => Errors while adding packages:

While selecting package versions:
error: unknown package: isobuild:isopack-2
Required by: vijayanant:meteor-yahoo-oauth 1.0.1

**Comment by vijayanant** [comment]
This is happening for meteor versions below 1.2.1

Any package published from 1.2.1 is not backward compatible !! 
Check this  https://github.com/meteor/meteor/issues/5054

**Comment by vijayanant** [comment]
Fixed now.
